USE fifa;
DROP TABLE IF EXISTS Players;
CREATE TABLE Players (
    Player_ID VARCHAR(50) PRIMARY KEY,
    Name VARCHAR(50),
    Age VARCHAR(50),
    Photo VARCHAR(50),
    Nationality VARCHAR(50),
    Flag VARCHAR(50),
    Overall VARCHAR(50),
    Potential VARCHAR(50),
    Club VARCHAR(50),
    Club_Logo VARCHAR(50),
    Player_Value_Euros VARCHAR(50),
    Wage_Euros VARCHAR(50),
    Preferred_Foot VARCHAR(50),
    International_Reputation VARCHAR(50),
    Weak_Foot VARCHAR(50),
    Skill_Moves VARCHAR(50),
    Work_Rate VARCHAR(50),
    Body_Type VARCHAR(50),
    Position VARCHAR(50),
    Jersey_Number VARCHAR(50),
    LS_Current VARCHAR(50),
    LS_Potential VARCHAR(50),
    ST_Current VARCHAR(50),
    ST_Potential VARCHAR(50),
    RS_Current VARCHAR(50),
    RS_Potential VARCHAR(50),
    LW_Current VARCHAR(50),
    LW_Potential VARCHAR(50),
    LF_Current VARCHAR(50),
    LF_Potential VARCHAR(50),
    CF_Current VARCHAR(50),
    CF_Potential VARCHAR(50),
    RF_Current VARCHAR(50),
    RF_Potential VARCHAR(50),
    RW_Current VARCHAR(50),
    RW_Potential VARCHAR(50),
    LAM_Current VARCHAR(50),
    LAM_Potential VARCHAR(50),
    CAM_Current VARCHAR(50),
    CAM_Potential VARCHAR(50),
    RAM_Current VARCHAR(50),
    RAM_Potential VARCHAR(50),
    LM_Current VARCHAR(50),
    LM_Potential VARCHAR(50),
    LCM_Current VARCHAR(50),
    LCM_Potential VARCHAR(50),
    CM_Current VARCHAR(50),
    CM_Potential VARCHAR(50),
    RCM_Current VARCHAR(50),
    RCM_Potential VARCHAR(50),
    RM_Current VARCHAR(50),
    RM_Potential VARCHAR(50),
    LWB_Current VARCHAR(50),
    LWB_Potential VARCHAR(50),
    LDM_Current VARCHAR(50),
    LDM_Potential VARCHAR(50),
    CDM_Current VARCHAR(50),
    CDM_Potential VARCHAR(50),
    RDM_Current VARCHAR(50),
    RDM_Potential VARCHAR(50),
    RWB_Current VARCHAR(50),
    RWB_Potential VARCHAR(50),
    LB_Current VARCHAR(50),
    LB_Potential VARCHAR(50),
    LCB_Current VARCHAR(50),
    LCB_Potential VARCHAR(50),
    CB_Current VARCHAR(50),
    CB_Potential VARCHAR(50),
    RCB_Current VARCHAR(50),
    RCB_Potential VARCHAR(50),
    RB_Current VARCHAR(50),
    RB_Potential VARCHAR(50),
    Crossing VARCHAR(50),
    Finishing VARCHAR(50),
    HeadingAccuracy VARCHAR(50),
    ShortPassing VARCHAR(50),
    Volleys VARCHAR(50),
    Dribbling VARCHAR(50),
    Curve VARCHAR(50),
    FKAccuracy VARCHAR(50),
    LongPassing VARCHAR(50),
    BallControl VARCHAR(50),
    Acceleration VARCHAR(50),
    SprintSpeed VARCHAR(50),
    Agility VARCHAR(50),
    Reactions VARCHAR(50),
    Balance VARCHAR(50),
    ShotPower VARCHAR(50),
    Jumping VARCHAR(50),
    Stamina VARCHAR(50),
    Strength VARCHAR(50),
    LongShots VARCHAR(50),
    Aggression VARCHAR(50),
    Interceptions VARCHAR(50),
    Positioning VARCHAR(50),
    Vision VARCHAR(50),
    Penalties VARCHAR(50),
    Composure VARCHAR(50),
    Marking VARCHAR(50),
    StandingTackle VARCHAR(50),
    SlidingTackle VARCHAR(50),
    GKDiving VARCHAR(50),
    GKHandling VARCHAR(50),
    GKKicking VARCHAR(50),
    GKPositioning VARCHAR(50),
    GKReflexes VARCHAR(50)
);

SELECT * FROM Players;

-- __________________________________________________________________________________________________
-- Creating Clubs_dim(clubs dimension) Table
Select Club, Club_Logo from Players;

DROP TABLE IF EXISTS Clubs_dim;
Create Table Clubs_dim(
	Club_ID VARCHAR(50) Primary Key,
    Club varchar(255) NOT NULL,
    Club_Logo varchar(255)
    );
    
Set @rownum := 0;    
Insert into Clubs_dim(Club_ID, Club, Club_Logo) 
select 
CONCAT('C', LPAD(@rownum := @rownum + 1, 5, '0')) as Club_ID, 
Club, 
Club_Logo
from (SELECT DISTINCT Club, Club_Logo FROM Players WHERE Club IS NOT NULL AND Club <> '') as club_data;

Select * from Clubs_dim;

select count(distinct Club) from Players;

-- ------------------------------------------------------


-- SET SQL_SAFE_UPDATES = 0;
-- Replace club names with unique club IDs in the Main Players Table


CREATE Table Players_after_clubs_extraction
SELECT 
	Player_ID,
    Name,
    Age,
    Photo,
    Nationality,
    Flag,
    Overall,
    Potential,
    -- p.Club as Club_1,
    c.Club_ID,
    -- c.Club,
    c.Club_Logo,
    Player_Value_Euros,
    Wage_Euros,
    Preferred_Foot,
    International_Reputation,
    Weak_Foot,
    Skill_Moves,
    Work_Rate,
    Body_Type,
    Position,
    Jersey_Number,
    LS_Current,
    LS_Potential,
    ST_Current,
    ST_Potential,
    RS_Current,
    RS_Potential,
    LW_Current,
    LW_Potential,
    LF_Current,
    LF_Potential,
    CF_Current,
    CF_Potential,
    RF_Current,
    RF_Potential,
    RW_Current,
    RW_Potential,
    LAM_Current,
    LAM_Potential,
    CAM_Current,
    CAM_Potential,
    RAM_Current,
    RAM_Potential,
    LM_Current,
    LM_Potential,
    LCM_Current,
    LCM_Potential,
    CM_Current,
    CM_Potential,
    RCM_Current,
    RCM_Potential,
    RM_Current,
    RM_Potential,
    LWB_Current,
    LWB_Potential,
    LDM_Current,
    LDM_Potential,
    CDM_Current,
    CDM_Potential,
    RDM_Current,
    RDM_Potential,
    RWB_Current,
    RWB_Potential,
    LB_Current,
    LB_Potential,
    LCB_Current,
    LCB_Potential,
    CB_Current,
    CB_Potential,
    RCB_Current,
    RCB_Potential,
    RB_Current,
    RB_Potential,
    Crossing,
    Finishing,
    HeadingAccuracy,
    ShortPassing,
    Volleys,
    Dribbling,
    Curve,
    FKAccuracy,
    LongPassing,
    BallControl,
    Acceleration,
    SprintSpeed,
    Agility,
    Reactions,
    Balance,
    ShotPower,
    Jumping,
    Stamina,
    Strength,
    LongShots,
    Aggression,
    Interceptions,
    Positioning,
    Vision,
    Penalties,
    Composure,
    Marking,
    StandingTackle,
    SlidingTackle,
    GKDiving,
    GKHandling,
    GKKicking,
    GKPositioning,
    GKReflexes
    
from Players AS p
LEFT JOIN Clubs_dim AS c 
ON p.Club = c.Club;

-- UPDATE Players AS p
-- LEFT JOIN Clubs_dim AS c 
-- ON p.Club = c.Club
-- SET p.Club = c.Club_ID;

SELECT * FROM players_after_clubs_extraction;


-- Remove the Club_Logo column from the Players table
-- ALTER TABLE Players
-- DROP COLUMN Club_Logo;

-- SET SQL_SAFE_UPDATES = 1;
-- _____________________________________________________________________________________________________

-- Creating Positions_dim Table 
Drop Table Positions_dim;
CREATE TABLE Positions_dim (
    Player_ID VARCHAR(100) PRIMARY KEY,
    Position VARCHAR(100),
    LS_Current VARCHAR(100),
    LS_Potential VARCHAR(100),
    ST_Current VARCHAR(100),
    ST_Potential VARCHAR(100),
    RS_Current VARCHAR(100),
    RS_Potential VARCHAR(100),
    LW_Current VARCHAR(100),
    LW_Potential VARCHAR(100),
    LF_Current VARCHAR(100),
    LF_Potential VARCHAR(100),
    CF_Current VARCHAR(100),
    CF_Potential VARCHAR(100),
    RF_Current VARCHAR(100),
    RF_Potential VARCHAR(100),
    RW_Current VARCHAR(100),
    RW_Potential VARCHAR(100),
    LAM_Current VARCHAR(100),
    LAM_Potential VARCHAR(100),
    CAM_Current VARCHAR(100),
    CAM_Potential VARCHAR(100),
    RAM_Current VARCHAR(100),
    RAM_Potential VARCHAR(100),
    LM_Current VARCHAR(100),
    LM_Potential VARCHAR(100),
    LCM_Current VARCHAR(100),
    LCM_Potential VARCHAR(100),
    CM_Current VARCHAR(100),
    CM_Potential VARCHAR(100),
    RCM_Current VARCHAR(100),
    RCM_Potential VARCHAR(100),
    RM_Current VARCHAR(100),
    RM_Potential VARCHAR(100),
    LWB_Current VARCHAR(100),
    LWB_Potential VARCHAR(100),
    LDM_Current VARCHAR(100),
    LDM_Potential VARCHAR(100),
    CDM_Current VARCHAR(100),
    CDM_Potential VARCHAR(100),
    RDM_Current VARCHAR(100),
    RDM_Potential VARCHAR(100),
    RWB_Current VARCHAR(100),
    RWB_Potential VARCHAR(100),
    LB_Current VARCHAR(100),
    LB_Potential VARCHAR(100),
    LCB_Current VARCHAR(100),
    LCB_Potential VARCHAR(100),
    CB_Current VARCHAR(100),
    CB_Potential VARCHAR(100),
    RCB_Current VARCHAR(100),
    RCB_Potential VARCHAR(100),
    RB_Current VARCHAR(100),
    RB_Potential VARCHAR(100)
);
Select * from positions_dim;
-- Select distinct count(Position) from players_after_clubs_extraction; 
  
Insert into positions_dim(
	Player_ID,
    Position,
    LS_Current,
    LS_Potential,
    ST_Current,
    ST_Potential,
    RS_Current,
    RS_Potential,
    LW_Current,
    LW_Potential,
    LF_Current,
    LF_Potential,
    CF_Current,
    CF_Potential,
    RF_Current,
    RF_Potential,
    RW_Current,
    RW_Potential,
    LAM_Current,
    LAM_Potential,
    CAM_Current,
    CAM_Potential,
    RAM_Current,
    RAM_Potential,
    LM_Current,
    LM_Potential,
    LCM_Current,
    LCM_Potential,
    CM_Current,
    CM_Potential,
    RCM_Current,
    RCM_Potential,
    RM_Current,
    RM_Potential,
    LWB_Current,
    LWB_Potential,
    LDM_Current,
    LDM_Potential,
    CDM_Current,
    CDM_Potential,
    RDM_Current,
    RDM_Potential,
    RWB_Current,
    RWB_Potential,
    LB_Current,
    LB_Potential,
    LCB_Current,
    LCB_Potential,
    CB_Current,
    CB_Potential,
    RCB_Current,
    RCB_Potential,
    RB_Current,
    RB_Potential) 
SELECT  
	Player_ID, 	
    Position,
    LS_Current,
    LS_Potential,
    ST_Current,
    ST_Potential,
    RS_Current,
    RS_Potential,
    LW_Current,
    LW_Potential,
    LF_Current,
    LF_Potential,
    CF_Current,
    CF_Potential,
    RF_Current,
    RF_Potential,
    RW_Current,
    RW_Potential,
    LAM_Current,
    LAM_Potential,
    CAM_Current,
    CAM_Potential,
    RAM_Current,
    RAM_Potential,
    LM_Current,
    LM_Potential,
    LCM_Current,
    LCM_Potential,
    CM_Current,
    CM_Potential,
    RCM_Current,
    RCM_Potential,
    RM_Current,
    RM_Potential,
    LWB_Current,
    LWB_Potential,
    LDM_Current,
    LDM_Potential,
    CDM_Current,
    CDM_Potential,
    RDM_Current,
    RDM_Potential,
    RWB_Current,
    RWB_Potential,
    LB_Current,
    LB_Potential,
    LCB_Current,
    LCB_Potential,
    CB_Current,
    CB_Potential,
    RCB_Current,
    RCB_Potential,
    RB_Current,
    RB_Potential
from players_after_clubs_extraction as positional_data;

Select * from positions_dim;
-- ___________________________________________________________________________________________________________
-- SELECT count(distinct Nationality) FROM players_after_clubs_extraction;

Create Table players_after_position_extraction2
SELECT Player_ID, 
	   Name, 
       Age, 
       Photo, 
       Nationality, 
       Flag, 
       Overall, 
       Potential, 
       Club_ID, 
       Player_Value_Euros,
       Wage_Euros, 
       Preferred_Foot, 
       International_Reputation, 
       Weak_Foot, 
       Skill_Moves, 
       Work_Rate, 
       Body_Type,
       Jersey_Number, 
       Crossing, 
       Finishing, 
       HeadingAccuracy, 
       ShortPassing, 
       Volleys, 
       Dribbling, 
       Curve, 
       FKAccuracy, 
       LongPassing, 
       BallControl, 
       Acceleration, 
       SprintSpeed, 
       Agility, 
       Reactions, 
       Balance, 
       ShotPower, 
       Jumping, 
       Stamina, 
       Strength, 
       LongShots, 
       Aggression, 
       Interceptions, 
       Positioning, 
       Vision, 
       Penalties, 
       Composure, 
       Marking, 
       StandingTackle, 
       SlidingTackle, 
       GKDiving, 
       GKHandling, 
       GKKicking, 
       GKPositioning, 
       GKReflexes
       
FROM players_after_clubs_extraction;
SELECT * FROM players_after_position_extraction2;
-- _______________________________________________________________________________________________________

-- Creating Nationality_dim Table 

Select Distinct 
Nationality, 
Flag 
From players_after_position_extraction2;

Create Table Nationality_dim(
	Nationality_ID VARCHAR(50) Primary Key,
    Nationality varchar(100) NOT NULL,
    Flag varchar(255)
    );
    
Select * from nationality_dim;
    
Set @rownum := 0;    
Insert into Nationality_dim(
    Nationality_ID,
    Nationality,
    Flag) 
select 
CONCAT('Nat', LPAD(@rownum := @rownum + 1, 3, '0')) as Nationality_ID, 
Nationality,
Flag
From (Select Distinct Nationality, Flag From players_after_position_extraction2) as Nationality_data;

-- _______________________________________________________________________________________________________

-- Replacing Nationality and Flag Columns from the players_after_position_extraction2 table by using Nationality_ID
Create Table players_after_Nationality_extraction3
Select 
Player_ID, 
	   Name, 
       Age, 
       Photo, 
--       pe.Nationality, 
--       pe.Flag,
       n.Nationality_ID,
--       n.Nationality, 
--       n.Flag,
       Overall, 
       Potential, 
       Club_ID, 
       Player_Value_Euros,
       Wage_Euros, 
       Preferred_Foot, 
       International_Reputation, 
       Weak_Foot, 
       Skill_Moves, 
       Work_Rate, 
       Body_Type,
       Jersey_Number, 
       Crossing, 
       Finishing, 
       HeadingAccuracy, 
       ShortPassing, 
       Volleys, 
       Dribbling, 
       Curve, 
       FKAccuracy, 
       LongPassing, 
       BallControl, 
       Acceleration, 
       SprintSpeed, 
       Agility, 
       Reactions, 
       Balance, 
       ShotPower, 
       Jumping, 
       Stamina, 
       Strength, 
       LongShots, 
       Aggression, 
       Interceptions, 
       Positioning, 
       Vision, 
       Penalties, 
       Composure, 
       Marking, 
       StandingTackle, 
       SlidingTackle, 
       GKDiving, 
       GKHandling, 
       GKKicking, 
       GKPositioning, 
       GKReflexes
From players_after_position_extraction2 as pe
Left Join nationality_dim as n
On pe.Nationality = n.Nationality;

SELECT * FROM players_after_nationality_extraction3;
-- __________________________________________________________________________________________________

-- Creating Players attribute table

Create table Players_Attributes_dim
Select Player_ID, 
	   Crossing, 
       Finishing, 
       HeadingAccuracy, 
       ShortPassing, 
       Volleys, 
       Dribbling, 
       Curve, 
       FKAccuracy, 
       LongPassing, 
       BallControl, 
       Acceleration, 
       SprintSpeed, 
       Agility, 
       Reactions, 
       Balance, 
       ShotPower, 
       Jumping, 
       Stamina, 
       Strength, 
       LongShots, 
       Aggression, 
       Interceptions, 
       Positioning, 
       Vision, 
       Penalties, 
       Composure, 
       Marking, 
       StandingTackle, 
       SlidingTackle, 
       GKDiving, 
       GKHandling, 
       GKKicking, 
       GKPositioning, 
       GKReflexes
From players_after_nationality_extraction3;
Select * from Players_Attributes_dim;
-- ___________________________________________________________________________________________________

-- Creating Final Players Fact Table
Create Table players_fact
Select 
Player_ID, 
	   Name, 
       Age, 
       Photo, 
       Nationality_ID,
       Overall, 
       Potential, 
       Club_ID, 
       Player_Value_Euros,
       Wage_Euros, 
       Preferred_Foot, 
       International_Reputation, 
       Weak_Foot, 
       Skill_Moves, 
       Work_Rate, 
       Body_Type,
       Jersey_Number
From players_after_nationality_extraction3;
Select * from players_fact;
